# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
dist: xenial

addons:
  apt:
    packages:
      - libxml2-dev # for XML
      - libgit2-dev # fpr git2r

r_binary_packages:
  - testthat
  - jsonlite
  - git2r
  - ps
  - processx
  - httr
  - dplyr
  - lubridate
  - purrr
  - stringr
  - ggplot2
  - knitr
  - rmarkdown
  - commonmark
  - highlight
  - xml2
  - roxygen2

r:
  - oldrel
  - release
  - devel
